spring:
  application:
    name: News App
  datasource:
    url: ${DB_URL}?TimeZone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      data-source-properties:
        ssl: true
        sslmode: require
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        jdbc:
          time_zone: Asia/Seoul
        type:
          preferred_instant_jdbc_type: TIMESTAMP_WITH_TIMEZONE
# Gemini API Configuration
gemini:
  api:
    key: ${GEMINI_API_KEY}
    model: gemini-2.5-flash-lite
springdoc:
  swagger-ui:
    # Swagger UI에 접속할 경로를 설정합니다.
    # 예시: http://localhost:8080/swagger-ui.html -> http://localhost:8080/swagger-ui.html
    path: /swagger-ui.html
    # Swagger UI 활성화/비활성화
    enabled: true

  api-docs:
    # OpenAPI 3.0 문서를 제공하는 경로를 설정합니다. (JSON/YAML)
    # 예시: http://localhost:8080/v3/api-docs -> http://localhost:8080/v3/api-docs
    path: /v3/api-docs
    # API 문서 활성화/비활성화
    enabled: true

logging:
  file:
    # 로그 파일이 저장될 경로와 기본 파일명입니다.
    name: logs/eyehope.log
  logback:
    rollingpolicy:
      # 위에서 지정한 eyehope.log 파일이 날짜가 지나면 어떤 패턴으로 바뀔지 정합니다.
      # 'logs/eyehope.%d{yyyy-MM-dd}.log'는 'logs/eyehope.2025-09-03.log' 와 같은 형태로 저장됩니다.
      file-name-pattern: logs/eyehope.%d{yyyy-MM-dd}.%i.log.gz
      # 로그 보관 기간을 정합니다. 30일이 지난 로그 파일은 자동으로 삭제됩니다.
      max-history: 30
      max-file-size: 10MB