spring:
  application:
    name: News App
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      data-source-properties:
        ssl: true
        sslmode: require
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Gemini API Configuration
gemini:
  api:
    key: ${GEMINI_API_KEY}
    model: gemini-2.0-flash-001
springdoc:
  swagger-ui:
    # Swagger UI에 접속할 경로를 설정합니다.
    # 예시: http://localhost:8080/swagger-ui.html -> http://localhost:8080/swagger-ui.html
    path: /swagger-ui.html
    # Swagger UI 활성화/비활성화
    enabled: true

  api-docs:
    # OpenAPI 3.0 문서를 제공하는 경로를 설정합니다. (JSON/YAML)
    # 예시: http://localhost:8080/v3/api-docs -> http://localhost:8080/v3/api-docs
    path: /v3/api-docs
    # API 문서 활성화/비활성화
    enabled: true