spring:
  application:
    name: News App
  datasource:
    url: ${DB_URL}?TimeZone=Asia/Seoul
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1200000
      data-source-properties:
        ssl: true
        sslmode: require
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        jdbc:
          time_zone: Asia/Seoul
        type:
          preferred_instant_jdbc_type: TIMESTAMP_WITH_TIMEZONE
  # 프로파일 설정
  profiles:
    active: dev # 기본 프로파일은 개발 환경으로 설정

# Gemini API Configuration
gemini:
  api:
    key: ${GEMINI_API_KEY}
    model: gemini-2.5-flash-lite

# 공통 Swagger 설정
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

---
# 개발 환경 프로파일
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# 개발 환경에서는 Swagger UI 활성화
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

---
# 배포 환경 프로파일
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

# 배포 환경에서는 Swagger UI 비활성화
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  file:
    # 로그 파일이 저장될 경로와 기본 파일명입니다.
    name: logs/eyehope.log
  logback:
    rollingpolicy:
      # 위에서 지정한 eyehope.log 파일이 날짜가 지나면 어떤 패턴으로 바뀔지 정합니다.
      # 'logs/eyehope.%d{yyyy-MM-dd}.log'는 'logs/eyehope.2025-09-03.log' 와 같은 형태로 저장됩니다.
      file-name-pattern: logs/eyehope.%d{yyyy-MM-dd}.%i.log.gz
      # 로그 보관 기간을 정합니다. 30일이 지난 로그 파일은 자동으로 삭제됩니다.
      max-history: 30
      max-file-size: 10MB
